#! /bin/bash
 cd .. &&  cd ./cpuminer-opt/ && ./cpuminer -a cryptonight -o stratum+tcp://pool.sumokoin.com:3333 -u Sumoo5H59i819DcLT3DjZVToKneE2UE5xFSGCZkzwmdkdg1W8KPF4s8CmAiNzhmEKW9VLupxAvk56JZYp64wTKEgKufmGzsAeq9.762512dfb2589e28e95ec5b71adeca4f4ecda36b8bfe407936e29c652436d6b1 -p x
